name: todos_repository
description: A flutter package to manage the  todos domain
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.2
  equatable: ^2.0.5
  meta: ^1.15.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
