// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzxt2EAHvwGPJIJmz5YkA9_fw7AqeZNgA',
    appId: '1:458700474749:web:5c4fd01f1235969cd42414',
    messagingSenderId: '458700474749',
    projectId: 'holberon-app',
    authDomain: 'holberon-app.firebaseapp.com',
    storageBucket: 'holberon-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMgAtTxHXRNqsdHsPlOoenBU8DeS5VpMs',
    appId: '1:458700474749:android:056f57d1db016e6fd42414',
    messagingSenderId: '458700474749',
    projectId: 'holberon-app',
    storageBucket: 'holberon-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJYNuj3G3NCjZlpESEF6LgQ75nBqxvyo',
    appId: '1:458700474749:ios:6162a756e49ff07bd42414',
    messagingSenderId: '458700474749',
    projectId: 'holberon-app',
    storageBucket: 'holberon-app.appspot.com',
    iosBundleId: 'com.example.verygoodcore.holberton-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvJYNuj3G3NCjZlpESEF6LgQ75nBqxvyo',
    appId: '1:458700474749:ios:c2c08f55dc1d8b10d42414',
    messagingSenderId: '458700474749',
    projectId: 'holberon-app',
    storageBucket: 'holberon-app.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzxt2EAHvwGPJIJmz5YkA9_fw7AqeZNgA',
    appId: '1:458700474749:web:65ff13057deb88ccd42414',
    messagingSenderId: '458700474749',
    projectId: 'holberon-app',
    authDomain: 'holberon-app.firebaseapp.com',
    storageBucket: 'holberon-app.appspot.com',
  );
}
